spring:
  application:
    name: kotlin_crud
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true